### ISSUE TITLE
The generate can't run in a project without a User model

### ISSUE THREAD

**Issue by augustocbx** [tomichj/invitation#3]
$ rails generate invitation:install --model "Security::User"
`invitation-817d25d87275/lib/invitation/configuration.rb:49:in 'initialize': undefined local variable or method 'configuration' for #<Invitation::Configuration:0x007fbe878c7948> (NameError)
        from /Users/augustocbx/.rvm/gems/ruby-2.3.1@grimes/bundler/gems/invitation-817d25d87275/lib/invitation/configuration.rb:71:in 'new'
        from /Users/augustocbx/.rvm/gems/ruby-2.3.1@grimes/bundler/gems/invitation-817d25d87275/lib/invitation/configuration.rb:71:in 'configuration'
        from /Users/augustocbx/.rvm/gems/ruby-2.3.1@grimes/bundler/gems/invitation-817d25d87275/lib/invitation/configuration.rb:79:in 'configure'
`

**Comment by augustocbx** [comment]
This bug was corrected checking if the class exists, in the line where the error happens.

**Comment by augustocbx** [comment]
This bug was corrected checking if the class exists, in the line where the error happens.
